### ISSUE TITLE
The Auto Mega-Issue

### ISSUE THREAD

**Issue by kenzierocks** [Team5818/kitbot-2017#2]
- [ ] Raise the collector arm to a set angle -- assigned to @Albert-Miao -- https://github.com/Team5818/kitbot-2017/tree/feature/raiseArmCollectorCmd
- [ ] Roll the collector rollers until the current spikes -- assigned to @kenzierocks
- [ ] Roll the collector rollers until the laser sensor is triggered -- assigned to @kenzierocks
- [ ] Spin the robot using the gyro -- assigned to @jproney -- https://github.com/Team5818/kitbot-2017/tree/feature/vision%2Bdriving
- [ ] Roll the climber winch until the current spikes -- assigned to @kenzierocks
- [ ] Single gear auto -- assigned to  `null`
- [ ] Multi-gear auto -- assigned to  `null`
- [ ] Far-peg single gear auto -- assigned to  `null`
- [ ] Do Nothing (This is a hard one) -- assigned to @km00700 
- [ ] Actuate Gear Piston -- assigned to @Albert-Miao -- https://github.com/Team5818/kitbot-2017/tree/feature/DeployGears
- [ ] Shift Drive Gears  -- assigned to @JacksonMcLaughlin

**Comment by jproney** [comment]
Spin the robot using the gyro

**Comment by Albert-Miao** [comment]
Raise the collector arm to a set angle

**Comment by Albert-Miao** [comment]
Aight we doooooooooooone

**Comment by jproney** [comment]
Gyro spinning command is finished

**Comment by JacksonMcLaughlin** [comment]
i will do the shift gears

**Comment by kenzierocks** [comment]
Closing in favor of the new realbot repo.
